### ISSUE TITLE
For a Data processing App from MessageHub changes an architecture diagram exists with use case highlight how each of the components is used in the architecture diagram

### ISSUE THREAD

**Issue by krook** [IBM/openwhisk-data-processing-message-hub#3]

**Comment by krook** [comment]
@silveyram Let's work with Thomas, Micah and @trevorbodz on the linkage from the Bluemix tile to a new Accelerate scenarios page like [OpenFridge](https://developer.ibm.com/accelerate/scenarios/openfridge/).

**Comment by krook** [comment]
Tracking content in the [wiki for this repository](https://github.com/IBM/ogs-data-processing-messagehub/wiki).

**Comment by romankhar** [comment]
@krook - the link you inserted above points to a doc with description of the Cloudant.

The README.md file in this repo has a diagram and explains the use case and a role of each component, so I think we can close this issue.
