### ISSUE TITLE
For a Data processing App from MessageHub changes GitHub repo exists with all the code a user needs to build out the use case example

### ISSUE THREAD

**Issue by krook** [IBM/openwhisk-data-processing-message-hub#4]

**Comment by romankhar** [comment]
not sure how do you expect to close this issue? Isn;t it what this repo is all about and therefore as soon as we are ok with this sample we can close this issue?

**Comment by romankhar** [comment]
@krook - I think this is now accomplished as the user can clone this repo and get the sample running.
