### ISSUE TITLE
Include new OpenWhisk Kafka PUBLISH action into the sample as soon as it is GA in OpenWhisk

### ISSUE THREAD

**Issue by romankhar** [IBM/openwhisk-data-processing-message-hub#8]
Within a next week or two OpenWhisk will have new action that allows publishing into Message Hub and Kafka. This sample needs to cover that as well.

**Comment by krook** [comment]
Need to evaluate the latest in the Message Hub package: https://github.com/apache/incubator-openwhisk-package-kafka

**Comment by krook** [comment]
At long last, this is implemented.
