### ISSUE TITLE
ZIP file as part of this repo?

### ISSUE THREAD

**Issue by romankhar** [IBM/openwhisk-data-processing-message-hub#9]
Dan, I have a zip file within this repo - I know it is not a good practice, but it has node-modules needed to run the sample. And I know it is definitely NOT a good practice to check in node-modules. Zip file gets auto-generated during deployment script running.

Q: - Do we keep or delete this zip file?

**Comment by krook** [comment]
@romankhar I think we'll do what we are now doing for the serverless-apis example. We add an `npm build` step.

**Comment by jzaccone** [comment]
Closing this since @krook implemented this already.
